-- Clean existing resources to prevent duplicates if necessary
-- DELETE FROM resources;

INSERT INTO resources (title, description, content_type, url, thumbnail_url, category, author, format, uploader_id, status) VALUES
('The Art of Focus', 'A comprehensive guide on deep work and maintaining concentration in the digital age.', 'guide', 'https://example.com/art-of-focus.pdf', 'https://images.unsplash.com/photo-1499750310107-5fef28a66643?auto=format&fit=crop&q=80&w=400', 'Productivity', 'James Clear', 'pdf', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'approved'),
('PostgreSQL Performance Tuning', 'Master deep database optimization techniques with this 2-hour video workshop.', 'course', 'https://example.com/db-tuning.mp4', 'https://images.unsplash.com/photo-1544383335-c533a39e8e60?auto=format&fit=crop&q=80&w=400', 'Tech', 'Alice Wilson', 'mp4', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'approved'),
('Digital Nomad Handbook 2026', 'Everything you need to know about working remotely from anywhere in the world.', 'ebook', 'https://example.com/nomad.pdf', 'https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&q=80&w=400', 'Career', 'Sarah Nomad', 'pdf', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'approved'),
('UI Design Mastery', 'From wireframes to high-fidelity prototypes. A practical video guide.', 'course', 'https://example.com/ui-mastery.mp4', 'https://images.unsplash.com/photo-1541462608141-ad437194368f?auto=format&fit=crop&q=80&w=400', 'Tech', 'Design Guru', 'mp4', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'pending'),
('The Growth Mindset', 'Transform your approach to challenges and learning with this insightful ebook.', 'ebook', 'https://example.com/growth.pdf', 'https://images.unsplash.com/photo-1493612276216-ee3925520721?auto=format&fit=crop&q=80&w=400', 'Wellness', 'Carol Dweck', 'pdf', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'approved'),
('Advanced Analytics with Python', 'Learn how to process large datasets and build predictive models.', 'course', 'https://example.com/python-data.mp4', 'https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400', 'Tech', 'Data Scientess', 'mp4', (SELECT id FROM users WHERE role = 'admin' LIMIT 1), 'approved');
